### PR TITLE
Added boxSize and objectFit properties to the product image

### LINKED ISSUE #57: fix overflow images on some products
## Describe the bug
fix overflow images on some products

To reproduce the error search a '1'
http://localhost:3000/search/1

image

### PR DESCRIPTION
**Pull request by khushab**
#### Issue Number
fixes ISSUE #57

#### Describe the changes you've made
Added boxSize and objectFit properties to the product image to stop overflow of image.

#### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by sanchis** [comment]
Hello, thanks for the fix.

Can you execute `npm run lint:fix` and upload the changes?
Have some lint errors. 
For more detail see the log https://github.com/sanchis/Madhardware/pull/58/checks?check_run_id=2646663298

**Comment by khushab** [comment]
> Hello, thanks for the fix.
> 
> Can you execute `npm run lint:fix` and upload the changes?
> Have some lint errors. 
> For more detail see the log https://github.com/sanchis/Madhardware/pull/58/checks?check_run_id=2646663298

Sure. Will try to fix it.

**Comment by khushab** [comment]
Hey I tried but couldn't solve the bug :(

**Comment by sanchis** [comment]
@khushab  Thanks for the contribution.
💯

**Comment by khushab** [comment]
> @khushab Thanks for the contribution.
> 💯

My pleasure.

**Pull request merged**
