### PR TITLE
Added issue template

### PR DESCRIPTION
**Pull request by 96RadhikaJadhav**
This PR will resolve issue #13 .

### CODE REVIEW

**Review by sanchis — APPROVED** [review]
Perfect Thanks!! 😀

**Comment by 96RadhikaJadhav** [comment]
> Perfect Thanks!! 😀

@sanchis  Can I add PR template also?

**Comment by sanchis** [comment]
> > Perfect Thanks!! 😀
> 
> @sanchis Can I add PR template also?

Sure.

**Comment by 96RadhikaJadhav** [comment]
@sanchis Okay, creating issue for it.

**Pull request merged**
